# Defaults file for the compatibility layer role.
---
custom_overlay_name: eessi
custom_overlay_source: git
custom_overlay_url: https://github.com/EESSI/gentoo-overlay.git

cvmfs_start_transaction: False
cvmfs_publish_transaction: False
cvmfs_abort_transaction_on_failures: False
cvmfs_repository: pilot.eessi-hpc.org

eessi_log_dir: "/tmp/eessi-logs"

package_sets: 
  - 2020.08

prefix_build_log: "{{ eessi_log_dir }}/compat-build.log"

gentoo_prefix_path: "/cvmfs/pilot.eessi-hpc.org/2020.10/compat/{{ eessi_host_arch }}"
prefix_singularity_command: "singularity run -B{{ gentoo_prefix_path }}:{{ gentoo_prefix_path }}"
prefix_source: "docker://eessi/bootstrap-prefix:centos8-{{ eessi_host_arch }}"
prefix_source_options: "{{ gentoo_prefix_path }} noninteractive"
prefix_install: "{{ prefix_singularity_command}} {{ prefix_source }} {{ prefix_source_options }}"

