# Install a specified list of sets and packages.
---
- name: "Update system"
  yum:
    name: '*'
    state: latest
  tags:
    - prefix

- name: "Install EPEL"
  yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    disable_gpg_check: yes
    state: present
  tags:
    - prefix

- name: "Install other requirements (singularity et al)"
  yum:
    name:
      - singularity
    state: present
  tags:
    - prefix

- name: "Get the username running the deployment (not root)"
  become: false
  shell: who | grep -v root | awk '{print $1}' | uniq
  register: username_on_host
  tags:
    - prefix

- name: "Create Gentoo prefix path and log directory -- {{ gentoo_prefix_path }} and  {{ eessi_log_dir }}"
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ username_on_host.stdout }}"
    group: "{{ username_on_host.stdout }}"
  with_items:
    - "{{ gentoo_prefix_path }}"
    - "{{ eessi_log_dir }}"
  tags:
    - prefix

- name: "Give {{ username_on_host.stdout }} recursive user and group ownership of /cvmfs"
  file:
    dest: "cvmfs"
    owner: "{{ username_on_host.stdout }}"
    group: "{{ username_on_host.stdout }}"
    recurse: yes
  tags:
    - prefix

- name: "Install Gentoo prefix via {{ prefix_install }}"
  become: false  
  shell: "{{ prefix_install }} | tee -a {{ prefix_build_log }} | grep -E '^(>>> Installing|\\* )'"
  tags:
    - prefix
